/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Hospital;

import DBUTIL.DBUTIL;
import MODEL.Validations;
import UI.LoginScreen;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import MODEL.HOSPITAL;
import java.util.Random;
import java.util.Vector;

/**
 *
 * @author Niharika
 */
public class Doctor extends javax.swing.JFrame {
Validations validations;
    /**
     * Creates new form RequestToPlasmacenter
     */
    
    
    ResultSet resultSet = null;
    Random rand = new Random();
    DBUTIL dbconn= new DBUTIL();
    Vector originalTableModel;
    public Doctor() {
        initComponents();
        validations = new Validations();
        populateTable();
        originalTableModel = (Vector) ((DefaultTableModel) tblDoctor.getModel()).getDataVector().clone();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblDoctor.getModel();
         Connection conn = dbconn.getConnection();
        model.setRowCount(0);
        
         
                  String selectSql = "SELECT doc_id, doc_name, spec, pager_id from doctors";

      Statement stmt;
       try {
            stmt = conn.createStatement();
       
            resultSet = stmt.executeQuery(selectSql);

             while (resultSet.next()) {
            
            Object[] row = new Object[4];
            row[0]=resultSet.getInt(1);
            row[1] = resultSet.getString(2);
            row[2] = resultSet.getString(3);
            row[3]= resultSet.getInt(4);
        
            
            model.addRow(row);
             }
             
            
             conn.close();
             
       }
       catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdoc_name = new javax.swing.JTextField();
        txtdoc_id = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtpager_id = new javax.swing.JTextField();
        specCombox = new javax.swing.JComboBox<>();
        valName = new javax.swing.JLabel();
        valSpecialisation = new javax.swing.JLabel();
        valPagerID = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblEmployeeName1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        valUsername = new javax.swing.JLabel();
        valPassword = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lbSearch = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        tblDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Name", "Specialization", "Pager ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoctor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 130, 600, 132);

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE DOCTOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 10, 250, 55);

        btnAdd.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(222, 570, 90, 24);

        btnUpdate.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(330, 270, 90, 24);

        btnDelete.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(450, 270, 90, 24);

        jLabel2.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 370, 120, 18);

        jLabel3.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jLabel3.setText("DOCTOR ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 330, 100, 18);

        jLabel4.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jLabel4.setText("SPECIALIZATION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 410, 130, 18);

        txtdoc_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoc_nameActionPerformed(evt);
            }
        });
        txtdoc_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdoc_nameKeyReleased(evt);
            }
        });
        getContentPane().add(txtdoc_name);
        txtdoc_name.setBounds(330, 370, 131, 31);

        txtdoc_id.setEditable(false);
        txtdoc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoc_idActionPerformed(evt);
            }
        });
        getContentPane().add(txtdoc_id);
        txtdoc_id.setBounds(330, 330, 131, 31);

        btnBack.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(710, 10, 90, 24);

        jLabel5.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jLabel5.setText("PAGER ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 450, 100, 18);

        txtpager_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpager_idKeyReleased(evt);
            }
        });
        getContentPane().add(txtpager_id);
        txtpager_id.setBounds(330, 450, 131, 31);

        specCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologist", "General Surgeon", "Orthopedician" }));
        specCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specComboxActionPerformed(evt);
            }
        });
        getContentPane().add(specCombox);
        specCombox.setBounds(330, 410, 179, 31);

        valName.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        getContentPane().add(valName);
        valName.setBounds(480, 370, 290, 20);

        valSpecialisation.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        getContentPane().add(valSpecialisation);
        valSpecialisation.setBounds(480, 410, 310, 20);

        valPagerID.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        getContentPane().add(valPagerID);
        valPagerID.setBounds(480, 450, 250, 20);

        lblEmployeeName.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        lblEmployeeName.setText("USER ID");
        getContentPane().add(lblEmployeeName);
        lblEmployeeName.setBounds(190, 490, 160, 18);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(330, 490, 130, 31);

        lblEmployeeName1.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        lblEmployeeName1.setText("PASSWORD ");
        getContentPane().add(lblEmployeeName1);
        lblEmployeeName1.setBounds(190, 530, 150, 18);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(330, 530, 130, 31);

        valUsername.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        getContentPane().add(valUsername);
        valUsername.setBounds(470, 500, 240, 20);

        valPassword.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        getContentPane().add(valPassword);
        valPassword.setBounds(480, 530, 270, 20);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch);
        txtSearch.setBounds(200, 70, 430, 30);

        lbSearch.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        lbSearch.setText("SEARCH");
        getContentPane().add(lbSearch);
        lbSearch.setBounds(110, 70, 90, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Hospital/hospital.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       var valid = true;
         if (!this.validations.ValidateName(txtdoc_name.getText()) ) {
            valName.setText("Name is Invalid");
            valid = false;
        }
         if (specCombox.getSelectedItem() == null || specCombox.getSelectedItem().toString().isEmpty()) {
            valSpecialisation.setText("Please Select Doctor Specialisation");
            valid = false;
        }
          if (!this.validations.ValidatePagerID(txtpager_id.getText()) ) {
            valPagerID.setText("Pager ID is Invalid");
            valid = false;
        }
          if (!this.validations.ValidateUsername(txtUsername.getText()) ) {
            valUsername.setText("Username is Invalid");
            valid = false;
        }

        String pass_word = String.valueOf(txtPassword.getPassword());
        if (!this.validations.ValidatePassword(pass_word) ) {
            valPassword.setText("Should be 4-12 character long");
            valid = false;
        }
        
        int SelectedRowIndex=tblDoctor.getSelectedRow();
        if(SelectedRowIndex<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a row to delete");
            
        return;
        }
        DefaultTableModel model =(DefaultTableModel) tblDoctor.getModel();
         int doc_id=(int) model.getValueAt(SelectedRowIndex, 0);
        String doc_name = txtdoc_name.getText();
       //int doc_id = Integer.valueOf(txtdoc_id.getText());
       //String contact_doc = jTextField3.getText();
       String spec = (String) specCombox.getSelectedItem(); 
       int pager_id = Integer.valueOf(txtpager_id.getText()); 
       // int hos_id = this.hos_id ;       
            // validate the text from text boxes 
       //DBUTIL dbconn= new DBUTIL();
        Connection conn = dbconn.getConnection();
        //do validation here.
        //check if the id already exists
  String SELECTHOSSQL = "update doctors set doc_name=?, spec=?, pager_id=?  where doc_id =?";
                PreparedStatement stmt; 
        try
        {
            stmt = conn.prepareStatement(SELECTHOSSQL);
       
             
            stmt.setString(1,doc_name); 
            //stmt.setInt(2,1);//put hos_id later.
            stmt.setString(2,spec);
            //stmt.setString(4, spec);
            stmt.setInt(3,pager_id);
            stmt.setInt(4,doc_id);
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(SelectedRowIndex<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a row to Update");
            
        return;
        }
        // to display in the text boxes          
        DefaultTableModel tblModel = (DefaultTableModel) tblDoctor.getModel();
              
       tblModel.setValueAt(doc_id,tblDoctor.getSelectedRow(), 0);
       tblModel.setValueAt(doc_name,tblDoctor.getSelectedRow(), 1);
       tblModel.setValueAt(spec,tblDoctor.getSelectedRow(), 2);
       tblModel.setValueAt(pager_id,tblDoctor.getSelectedRow(), 3);
       
       
      JOptionPane.showMessageDialog(this,"Doctor data Updated");

//  txtdoc_name.setText("");
//  txtdoc_id.setText("");
//  txtpager_id.setText("");
   populateTable();
  setTextNull();  
      setValidationNull();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       var valid = true;
         if (!this.validations.ValidateName(txtdoc_name.getText()) ) {
            valName.setText("Name is Invalid");
            valid = false;
        }
         if (specCombox.getSelectedItem() == null || specCombox.getSelectedItem().toString().isEmpty()) {
            valSpecialisation.setText("Please Select Doctor Specialisation");
            valid = false;
        }
          if (!this.validations.ValidatePagerID(txtpager_id.getText()) ) {
            valPagerID.setText("Pager ID is Invalid");
            valid = false;
        }
          if (!this.validations.ValidateUsername(txtUsername.getText()) ) {
            valUsername.setText("Username is Invalid");
            valid = false;
        }

        String pass_word = String.valueOf(txtPassword.getPassword());
        if (!this.validations.ValidatePassword(pass_word) ) {
            valPassword.setText("Should be 4-12 character long");
            valid = false;
        }
         
       String doc_name = txtdoc_name.getText();
       //int doc_id = Integer.valueOf(txtdoc_id.getText());
       int doc_id = rand.nextInt(1, 100);
       String spec = (String) specCombox.getSelectedItem(); 
       int pager_id = Integer.valueOf(txtpager_id.getText());
       int user_id = Integer.valueOf(txtUsername.getText()); 
       String password = txtPassword.getText(); 
       int dochos_id = HOSPITAL.getHos_id();
       
       
       //DBUTIL dbconn= new DBUTIL();
        Connection conn = dbconn.getConnection();
        //do validation here.
        
        //check if the id already exists
        String INSERTLOGIN = "insert into logins(user_id, pass_word, role_id) values (?,?,?)";
        String INSERTDOCSQL = "insert into doctors(doc_id, hos_id, doc_name, spec, pager_id, user_id) values (?,?,?,?,?,?)";
        // or handle exceptions here. 
        PreparedStatement stmt1, STMT2; 
        try
        {
            stmt1 = conn.prepareStatement(INSERTLOGIN);
            STMT2 = conn.prepareStatement(INSERTDOCSQL);
            
            stmt1.setInt(1,user_id); 
            stmt1.setString(2, password);
            stmt1.setInt(3, 4);
       
            stmt1.executeUpdate(); 
            
            STMT2.setInt(1,doc_id); 
            STMT2.setInt(2,dochos_id);//put hos_id later.
            STMT2.setString(3,doc_name);
            STMT2.setString(4, spec);
            STMT2.setInt(5,pager_id);
            STMT2.setInt(6,user_id);
            STMT2.executeUpdate();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }

           JOptionPane.showMessageDialog(this,"Doctor Added");

       populateTable(); 
   setTextNull();  
      setValidationNull();
  //stop
  
  txtdoc_name.setText("");
  txtdoc_id.setText("");
  txtpager_id.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.hide();
        HospitalWorkArea frame = new HospitalWorkArea();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtdoc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoc_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoc_idActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    Connection conn = dbconn.getConnection();
         int SelectedRowIndex=tblDoctor.getSelectedRow();
        if(SelectedRowIndex<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a row to delete");
            
        return;
        }
        DefaultTableModel model =(DefaultTableModel) tblDoctor.getModel();
        
          int doc_id=(int) model.getValueAt(SelectedRowIndex, 0);
       
         conn = dbconn.getConnection();
         //int doc_id = Integer.valueOf(txtdoc_id.getText());
          String selectSql = "Delete from doctors where doc_id=?";
     PreparedStatement stmt;
      try {
             
             stmt=conn.prepareStatement(selectSql);
             
                 stmt.setInt(1, doc_id);
                                   
              stmt.executeUpdate();
          conn.close();
          } catch (SQLException ex) {
              Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
          }
    
         
        JOptionPane.showMessageDialog(this, "Doctor Deleted");
        populateTable();
//        txtdoc_name.setText("");
//        txtdoc_id.setText("");
//        txtpager_id.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorMouseClicked
    DefaultTableModel tblModel = (DefaultTableModel) tblDoctor.getModel();
    
    String doc_id = tblModel.getValueAt(tblDoctor.getSelectedRow(),0).toString();
    String doc_name = tblModel.getValueAt(tblDoctor.getSelectedRow(),1).toString();
    String spec = tblModel.getValueAt(tblDoctor.getSelectedRow(),2).toString();
    String pager_id = tblModel.getValueAt(tblDoctor.getSelectedRow(),3).toString();
    
    txtdoc_name.setText(doc_name);
    txtdoc_id.setText(doc_id);
    txtpager_id.setText(pager_id); 
    
     setValidationNull();

        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDoctorMouseClicked

    private void txtdoc_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoc_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoc_nameActionPerformed

    private void specComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specComboxActionPerformed
        // TODO add your handling code here:
        Object plasma = specCombox.getSelectedItem();
        

        if (plasma  == null || plasma .toString().equals("")) {
            valSpecialisation.setText("Please Select Specialization");
            specCombox.removeAllItems();
           valSpecialisation.setText(null);
        } else {
            specCombox.setSelectedItem("");
        }
    }//GEN-LAST:event_specComboxActionPerformed

    private void txtdoc_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdoc_nameKeyReleased
        // TODO add your handling code here:
        if (!this.validations.ValidateName(txtdoc_name.getText()) ) {
            valName.setText("Name is Invalid");
        }
        else {
            valName.setText(null);
        }
    }//GEN-LAST:event_txtdoc_nameKeyReleased

    private void txtpager_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpager_idKeyReleased
        // TODO add your handling code here:
                if (!this.validations.ValidatePagerID(txtpager_id.getText()) ) {
            valPagerID.setText("Pager ID is Invalid");
        }
        else {
            valPagerID.setText(null);
        }
    }//GEN-LAST:event_txtpager_idKeyReleased

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblDoctor.getModel();

        model.setRowCount(0);
        for (Object rows : originalTableModel) {
            Vector rowVector = (Vector) rows;
            for (Object column : rowVector) {
                if (column.toString().toLowerCase().contains(txtSearch.getText())) {
                    //content found so adding to table
                    model.addRow(rowVector);
                    break;
                }
            }

        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }
     private void setTextNull() {
     
         txtdoc_name.setText(null);
         txtdoc_id.setText(null);
         txtUsername.setText(null);
         txtPassword.setText(null);
         txtpager_id.setText(null);
         specCombox.setSelectedItem(null);
  
    }
    private void setValidationNull() {
        valName.setText(null);
        valSpecialisation.setText(null);
        valPagerID.setText(null);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeeName1;
    private javax.swing.JComboBox<String> specCombox;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtdoc_id;
    private javax.swing.JTextField txtdoc_name;
    private javax.swing.JTextField txtpager_id;
    private javax.swing.JLabel valName;
    private javax.swing.JLabel valPagerID;
    private javax.swing.JLabel valPassword;
    private javax.swing.JLabel valSpecialisation;
    private javax.swing.JLabel valUsername;
    // End of variables declaration//GEN-END:variables
}
