/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Hospital;

import DBUTIL.DBUTIL;
import UI.Admin.AdminHospital;
import UI.LoginScreen;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Niharika
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    ResultSet resultSet, resultSet1, resultSet2 = null;
    DBUTIL dbconn= new DBUTIL();
    
    public Patient() {
        initComponents();
        UpdateComboxdoc_id();
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
         Connection conn = dbconn.getConnection();
        model.setRowCount(0);
        
         
       String selectSql = "SELECT patient_id,patient_name,age, gender, doc_id,address from patients ";
        

      Statement stmt;
       try {
            stmt = conn.createStatement();
       
            resultSet = stmt.executeQuery(selectSql);

             while (resultSet.next()) {
            
            Object[] row = new Object[6];
            row[0]=resultSet.getInt(1);
            row[1] = resultSet.getString(2);
            row[2] = resultSet.getInt(3);
            row[3]=resultSet.getString(4);
            row[4]=resultSet.getInt(5);
            row[5]=resultSet.getString(6);
            
            
            model.addRow(row);
             }
             
            
             conn.close();
             
       }
       catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpat_id = new javax.swing.JTextField();
        txtpat_name = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        Gender = new javax.swing.JLabel();
        comboxgender = new javax.swing.JComboBox<>();
        comboxdoc_id = new javax.swing.JComboBox<>();
        txtage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Gender1 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("    ADD PATIENT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(255, 21, 175, 39);

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Age", "Gender", "Doctor ID", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatient);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(27, 66, 888, 180);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 380, 80, 17);

        jLabel3.setText("Patient ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 350, 56, 17);

        jLabel4.setText("Age ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 410, 26, 17);
        getContentPane().add(txtpat_id);
        txtpat_id.setBounds(410, 350, 138, 23);

        txtpat_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpat_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txtpat_name);
        txtpat_name.setBounds(410, 380, 138, 23);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(300, 590, 72, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(590, 260, 73, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(690, 260, 72, 23);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(85, 31, 72, 23);

        Gender.setText("Address");
        getContentPane().add(Gender);
        Gender.setBounds(280, 520, 84, 17);

        comboxgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        getContentPane().add(comboxgender);
        comboxgender.setBounds(410, 440, 138, 23);

        getContentPane().add(comboxdoc_id);
        comboxdoc_id.setBounds(410, 480, 138, 23);

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        getContentPane().add(txtage);
        txtage.setBounds(410, 410, 138, 23);

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 440, 43, 17);

        Gender1.setText("Doctor");
        getContentPane().add(Gender1);
        Gender1.setBounds(280, 480, 38, 17);

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtaddress);
        txtaddress.setBounds(410, 520, 138, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpat_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpat_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpat_nameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       //int pat_id = Integer.valueOf(txtpat_name.getText());
       int SelectedRowIndex=tblPatient.getSelectedRow();
        if(SelectedRowIndex<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a row to delete");
            
        return;
        }
        DefaultTableModel model =(DefaultTableModel) tblPatient.getModel();
         int pat_id=(int) model.getValueAt(SelectedRowIndex, 0);
         
         
       txtpat_id.setVisible(false);
       String patient_name = txtpat_name.getText();
       int age = Integer.valueOf(txtage.getText()); 
       String gender = (String) comboxgender.getSelectedItem();
       int doc_id = Integer.valueOf((String)comboxdoc_id.getSelectedItem());
       String address = txtaddress.getText();
       //DBUTIL dbconn= new DBUTIL();
        Connection conn = dbconn.getConnection();
        //do validation here.
        //check if the id already exists
                String UPDATEPATIENTSQL = "update patients set patient_name=?, "
                        + "age=?, gender=?, doc_id=?, address=? where patient_id =?";

        PreparedStatement stmt; 
         
        try
        {
            stmt = conn.prepareStatement(UPDATEPATIENTSQL);
       
             
            stmt.setString(1,patient_name); 
            stmt.setInt(2,age);
            stmt.setString(3,gender);
            stmt.setInt(4,doc_id);
            stmt.setString(5,address); 
            stmt.setInt(6,pat_id);
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      JOptionPane.showMessageDialog(this,"Patient data Updated");

  txtpat_name.setText("");
  txtpat_id.setText("");
  txtage.setText("");
  txtaddress.setText("");
  populateTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      int patinet_id = Integer.valueOf(txtpat_id.getText());
       String patient_name = txtpat_name.getText();
       int age = Integer.valueOf(txtage.getText()); 
       String gender = (String) comboxgender.getSelectedItem();
        
       int doc_id = Integer.valueOf((String) comboxdoc_id.getSelectedItem());
       String address = txtaddress.getText();
       //DBUTIL dbconn= new DBUTIL();
        Connection conn = dbconn.getConnection();
        //do validation here.
        if(txtpat_id.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter patient id");
           return;
        }
        if(txtpat_name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter pager id");
            return;
        }
        if(txtage.getText().matches("\\d+"))
        {
            JOptionPane.showMessageDialog(this, "Please enter valid age in digits");
            return;
        }
        if(txtaddress.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter valid address");
            return;
        }
        //check if the id already exists
                String INSERTHOSSQL = "insert into patients(patient_id,patient_name,"
                        + "age,gender, doc_id, address) values (?,?,?,?,?,?) ";

        PreparedStatement stmt; 
        try
        {
            stmt = conn.prepareStatement(INSERTHOSSQL);
       
             
            stmt.setInt(1,patinet_id); 
            stmt.setString(2,patient_name);
            stmt.setInt(3,age);
            stmt.setString(4,gender);
            stmt.setInt(5,doc_id);
            stmt.setString(6,address);
            
            
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

           JOptionPane.showMessageDialog(this,"Patient Added");

       populateTable(); 
   
  //stop
  txtpat_name.setText("");
  txtpat_id.setText("");
  txtage.setText("");
  txtaddress.setText("");
  //populateTable();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    Connection conn = dbconn.getConnection();
         int SelectedRowIndex=tblPatient.getSelectedRow();
        if(SelectedRowIndex<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a row to delete");
            
        return;
        }
        DefaultTableModel model =(DefaultTableModel) tblPatient.getModel();
         int pat_id=(int) model.getValueAt(SelectedRowIndex, 0);
       
         conn = dbconn.getConnection();
         //int pat_id = Integer.valueOf(txtpat_id.getText());
          String selectSql = "Delete from patients where patient_id=?";
     PreparedStatement stmt;
      try {
             
             stmt=conn.prepareStatement(selectSql);
             
                 stmt.setInt(1, pat_id);
                                   
              stmt.executeUpdate();
          conn.close();
          } catch (SQLException ex) {
              Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
          }
    
         
        JOptionPane.showMessageDialog(this, "Patient Deleted");
        populateTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    this.hide();
        HospitalWorkArea frame = new HospitalWorkArea();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
    DefaultTableModel tblModel = (DefaultTableModel) tblPatient.getModel();

        // set data to textfield when raw is selected

        String patient_id = tblModel.getValueAt(tblPatient.getSelectedRow(),0).toString();
        String patient_name = tblModel.getValueAt(tblPatient.getSelectedRow(),1).toString();
        String age = tblModel.getValueAt(tblPatient.getSelectedRow(),2).toString();
        String gender = tblModel.getValueAt(tblPatient.getSelectedRow(),3).toString();
        String doc_id = tblModel.getValueAt(tblPatient.getSelectedRow(),4).toString();
        String address = tblModel.getValueAt(tblPatient.getSelectedRow(),5).toString();
      
        

        txtpat_id.setText(String.valueOf(patient_id));
        txtpat_name.setText(patient_name);
        txtage.setText(age);
        //comboxgender.
        //comboxdoc_id.
        txtaddress.setText(address);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientMouseClicked

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Gender1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboxdoc_id;
    private javax.swing.JComboBox<String> comboxgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtpat_id;
    private javax.swing.JTextField txtpat_name;
    // End of variables declaration//GEN-END:variables

    private void UpdateComboxdoc_id() {
        Connection conn = dbconn.getConnection();
        String SELECTSQL1 = "select doc_id from doctors where hos_id =?";
        //String SELECTSQL2 = "SELECT PC_ID FROM PLASMAC";
        // int hos_id = this.hos_id ; 

        PreparedStatement stmt1,stmt2; 
        try
        {
            stmt1 = conn.prepareStatement(SELECTSQL1);
            
            stmt1.setInt(1,1);// later change it to stmt1.setInt(1,hos_id); 
            
            resultSet1 = stmt1.executeQuery();
            
            
            
            while(resultSet1.next())
            {
                comboxdoc_id.addItem(resultSet1.getString(1));
            }
            
       
             
            
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
